version: '3.8'

services:
  backend:
    image: python3.9:latest
    container_name: django
    volumes:
      - media:./media
      - static:/static:ro
    command: 'python manage.py migrate && python manage.py runserver 8000'
    build: ./backend
    env_file:
      - .env
    ports:
      - '8000:8080'
    
  db:
    image: postgres:latest
    container_name: db
    # volumes:
      # - postgres:./
    ports:
      - '5432:5432'
volumes:
  - media
  - static
